### PR TITLE
fix(checkbox): improved layout. Fixed a checked state management

### LINKED ISSUE #275: Checkbox without label renders incorrectly
With label:
checkbox with label

Without label:
checkbox without label

Checkbox should keep block size without text in label.

### PR DESCRIPTION
**Pull request by aleks-elkin**
- Fixed #275 

- Fixed a `checked` state management. Before there could be unexpected behaviour:
  - render checkbox in `checked` state
  - User unchecks it.
  - set `checked` attribute from code.
  - Now it will have a `checked` attribute but will render unchecked. If user will click on it, a `checked` attribute removed but checkbox rendered in checked state.

- Added a few knobs to a story.

### CODE REVIEW

File: packages/components/checkbox/src/checkbox.js [hunk 1]
```diff
@@ -36,18 +36,17 @@ export class TSCheckbox extends TSElement {
...
-					@click="${this.onClick}"
 					.name="${this.name}"
 					.value="${this.value}"
 					?checked="${this.checked}"
 					?disabled="${this.disabled}"
 				/>
-				<span></span>
-			</label>
+				<div class="checkbox"></div>
+				${this.label}
```
Comment (esmailpour-hosein) [inline packages/components/checkbox/src/checkbox.js:48]: Since we are not forcing to have text for the `label`, I think it does make sense to have slot for it to be customizable

Comment (aleks-elkin) [reply packages/components/checkbox/src/checkbox.js:48]: I'm not sure what do you mean by this, can you explain a bit more? Currently we don't have any slots and do not support any customisation for a label.

Comment (esmailpour-hosein) [reply packages/components/checkbox/src/checkbox.js:48]: Since developers can just don't provide text for the label and put it next some other stuff like an image or icon, then maybe we can replace attribute with slot in this case, to let them put icon, image, etc. in the slot, so they can have the benefit of triggering checkbox by click on the label as well.

Comment (esmailpour-hosein) [reply packages/components/checkbox/src/checkbox.js:48]: Right now, they can just put an empty checkbox and next to it, use an image, and with some custom js get the similar functionality

Comment (aleks-elkin) [reply packages/components/checkbox/src/checkbox.js:48]: Ok, I see now. But how checkbox should be vertically aligned with this content? Also, I think we need to discuss it with UI/UX team first, do we want to provide such functionality.
And I suggest to implement it in a separate PR, since it will be a feature, not a fix.

Comment (esmailpour-hosein) [reply packages/components/checkbox/src/checkbox.js:48]: Sure we can do it in a separate PR 👍 
But it's not a feature to provide, it's already achievable, only in a bit hacky way.

**Comment by esmailpour-hosein** [comment]
Please check the IE11 screenshots

File: packages/components/checkbox/src/checkbox.js (hunk 1 above)
Comment (aleks-elkin) [reply packages/components/checkbox/src/checkbox.js:48]: I mean, that In terms of standard `ts-checkbox` functionality it will be considered as feature, because right now you cannot achieve this behaviour declaratively, without additional code on application side.
Of course you can implement many additional features on application side, but it doesn't mean that it's `native` implementation should be considered as a fix :)

**Comment by esmailpour-hosein** [comment]
There is an issue in IE11 for the Happo test which is not reproducible in browserstack. We'll take care of the issue later if anyone encountered this, to unblock this PR.
